version: "3"

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - "6379:6379"
    mem_limit: 128m
  django: &server
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: python

    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - celery
    mem_limit: 128m

  celery:
    <<: *server
    command: python -m celery -A mesada worker -B --loglevel=DEBUG
    links:
      - redis
    mem_limit: 128m
