version: "3"

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - "6379:6379"
    #mem_limit: 1000m
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_tutorial_django
    volumes:
      - ./dockerexample:/var/www/djangoproject
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - celery
    #mem_limit: 1000m

  celery:
    image: docker_tutorial_django
    build: .
    command: celery -A dockerexample worker -B --loglevel=DEBUG
    volumes:
      - ./dockerexample:/var/www/djangoproject
    links:
      - redis
    #mem_limit: 1000m
