version: "3"

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - "6379:6379"
    #mem_limit: 1000m
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: python
    volumes:
      - ./django_server:/app
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - celery
    #mem_limit: 1000m

  celery:
    image: python
    build: .
    command: celery -A mesada worker -B --loglevel=DEBUG
    volumes:
      - ./django_server:/app
    links:
      - redis
    #mem_limit: 1000m
