branch-defaults:
  default:
    environment: mesada-test-testing
    group_suffix: null
  dev:
    environment: mesada-usa-testing
  master:
    environment: mesada-usa-prod
global:
  application_name: mesada-usa-api
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
