# Generated by Django 3.1.4 on 2021-01-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Success"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
            ),
        )
    ]
