# Generated by Django 3.1.4 on 2021-01-30 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("order", "0002_auto_20210128_1846")]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("transfer", "Transfer"),
                            ("withdrawal", "Withdrawal"),
                            ("galactus_transaction", "Galactus Transaction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("error", "Error"), ("success", "Success")],
                        max_length=10,
                    ),
                ),
                ("details", models.JSONField(null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
        )
    ]
