# Generated by Django 3.1.4 on 2020-12-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('alias', models.CharField(blank=True, max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clabe', models.CharField(max_length=18)),
                ('bank_name', models.CharField(max_length=256)),
                ('client_recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
    ]
