# Generated by Django 3.1.4 on 2020-12-22 20:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ('first_name', 'last_name', 'alias')},
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='client_recipient',
        ),
        migrations.AddField(
            model_name='user',
            name='recipients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.recipient'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='clabe',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(code='invalid_clabe', message='Clabe must have 18 digits', regex='\\d{18}')]),
        ),
    ]
