# Generated by Django 3.1.4 on 2021-01-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0002_auto_20210120_1705")]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="alias",
            field=models.CharField(blank=True, max_length=256, null=True),
        )
    ]
