# Generated by Django 3.1.4 on 2021-01-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_auto_20201229_1422"),
        ("account", "0002_user_is_phone_verified"),
    ]

    operations = []
