# Generated by Django 3.1.4 on 2021-01-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0002_user_birth_date")]

    operations = [migrations.RemoveField(model_name="user", name="postal_code")]
