# Generated by Django 3.1.4 on 2021-01-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210120_2241'),
        ('account', '0004_recipient_phone'),
        ('account', '0004_remove_user_is_phone_verified'),
    ]

    operations = [
    ]
