# Generated by Django 3.1.4 on 2021-01-25 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0009_auto_20210122_2043")]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="bank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bbva", "Bbva"),
                    ("banamex", "Banamex"),
                    ("banorte", "Banorte"),
                    ("santander", "Santander"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="clabe",
            field=models.CharField(
                blank=True,
                max_length=18,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_clabe",
                        message="Clabe must have 18 digits",
                        regex="\\d{18}",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="first_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="last_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
