# Generated by Django 3.1.4 on 2021-01-25 18:39

from django.db import migrations, models

import mesada.account.models


class Migration(migrations.Migration):

    dependencies = [("account", "0010_auto_20210125_1534")]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="alias",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="phone",
            field=mesada.account.models.PossiblePhoneNumberField(
                blank=True, default="", max_length=128, region=None
            ),
        ),
    ]
