# Generated by Django 3.1.4 on 2021-01-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircleTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(max_length=256)),
                ('source_type', models.CharField(max_length=256)),
                ('source_id', models.CharField(max_length=256)),
                ('destination_type', models.CharField(max_length=256)),
                ('destination_address', models.CharField(max_length=256)),
                ('destination_chain', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
