# Generated by Django 3.1.4 on 2021-01-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transfer", "0003_auto_20210125_2100"),
        ("transfer", "0003_auto_20210125_1842"),
    ]

    operations = []
