# Generated by Django 3.1.4 on 2020-12-23 20:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethods", old_name="type_method", new_name="type"
        ),
        migrations.RenameField(
            model_name="paymentmethods", old_name="updated_at", new_name="updated"
        ),
        migrations.RemoveField(model_name="paymentmethods", name="created_at"),
        migrations.AddField(
            model_name="paymentmethods",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="paymentmethods",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name="paymentmethods",
            name="network",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="paymentmethods",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethods",
            name="verification_avs",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="city",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="country_code",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="district",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="email",
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="exp_month",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="exp_year",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(2050)],
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="last_digits",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="postal_code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name="paymentmethods",
            name="verification_cvv",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
