# Generated by Django 3.1.4 on 2021-01-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='payment_token',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='processor_token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
