# Generated by Django 3.1.4 on 2021-01-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("payment", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="paymentmethods",
            old_name="payment_token",
            new_name="payment_method_token",
        )
    ]
