# Generated by Django 3.1.4 on 2021-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payment", "0004_auto_20210107_1615")]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_token",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="payment",
            name="merchant_id",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="payment",
            name="merchant_wallet_id",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="payment", name="cancel", field=models.JSONField(null=True)
        ),
        migrations.AlterField(
            model_name="payment", name="fees", field=models.JSONField(null=True)
        ),
        migrations.AlterField(
            model_name="payment", name="refunds", field=models.JSONField(null=True)
        ),
        migrations.AlterField(
            model_name="payment",
            name="risk_evaluation",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="payment", name="verification", field=models.JSONField(null=True)
        ),
    ]
