# Generated by Django 3.1.4 on 2021-01-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SendEmailSendgridEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("causes", models.CharField(max_length=150)),
                ("created", models.DateField(auto_now_add=True)),
                ("template_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SendgridTemplates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("new-customer", "New Customer")], max_length=150
                    ),
                ),
                ("template_id", models.CharField(max_length=100)),
            ],
            options={"unique_together": {("name",)}},
        ),
    ]
