# Generated by Django 3.1.4 on 2021-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("checkout", "0003_auto_20210128_1611")]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="checkout_token",
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
    ]
